import { jsPDF } from "jspdf";

/**
 * Analytics Export Utility
 * Generates a professional PDF report from analytics data
 */

export const exportAnalyticsReport = {
  /**
   * Generates and downloads a PDF report
   * @param {Object} data - The aggregated analytics data
   * @param {Object} insights - The generated AI insights
   * @param {string} userName - The user's name
   */
  generatePDF: async (data, insights, userName = "User") => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const timestamp = new Date().toLocaleString();

      // --- Header ---
      doc.setFillColor(15, 23, 42); // Dark slate
      doc.rect(0, 0, pageWidth, 40, "F");
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("ProCV Lite", 20, 20);
      
      doc.setFontSize(12);
      doc.setFont("helvetica", "normal");
      doc.text("Professional Analytics Report", 20, 30);
      
      doc.setFontSize(10);
      doc.text(timestamp, pageWidth - 20, 25, { align: "right" });

      // --- Section: User Overview ---
      let y = 55;
      doc.setTextColor(15, 23, 42);
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.text(`Performance Overview for ${userName}`, 20, y);
      
      y += 10;
      doc.setDrawColor(226, 232, 240);
      doc.line(20, y, pageWidth - 20, y);
      
      y += 15;
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.text("Key Metrics:", 20, y);
      
      y += 10;
      doc.setFont("helvetica", "normal");
      const metrics = [
        ["Total CVs:", data.overview.totalCvs.toString()],
        ["Total Profile Views:", data.overview.totalViews.toString()],
        ["Total Downloads:", data.overview.totalDownloads.toString()],
        ["Average ATS Score:", `${data.overview.avgAtsScore}%`],
        ["AI Health Score:", `${insights.healthScore}/100`]
      ];
      
      metrics.forEach(([label, value]) => {
        doc.text(label, 25, y);
        doc.text(value, 100, y);
        y += 8;
      });

      // --- Section: AI Recommendations ---
      y += 10;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("Strategic Recommendations:", 20, y);
      
      y += 8;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      
      if (insights.recommendations.length > 0) {
        insights.recommendations.forEach((rec, i) => {
          doc.setFont("helvetica", "bold");
          doc.text(`${i + 1}. ${rec.text}`, 20, y);
          y += 5;
          doc.setFont("helvetica", "normal");
          const splitDesc = doc.splitTextToSize(rec.desc, pageWidth - 40);
          doc.text(splitDesc, 25, y);
          y += (splitDesc.length * 5) + 5;
        });
      } else {
        doc.text("No specific recommendations at this time. Keep up the great work!", 25, y);
        y += 10;
      }

      // --- Section: Top Skills ---
      y += 10;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("Skill Intelligence:", 20, y);
      
      y += 10;
      if (data.skills.top.length > 0) {
        data.skills.top.slice(0, 8).forEach((skill, i) => {
          doc.setFillColor(241, 245, 249);
          doc.rect(20, y - 5, pageWidth - 40, 8, "F");
          doc.setFont("helvetica", "normal");
          doc.text(skill.name, 25, y);
          doc.text("Strong", pageWidth - 30, y, { align: "right" });
          y += 10;
        });
      } else {
        doc.text("Insufficient skill data available.", 25, y);
        y += 10;
      }

      // --- Footer ---
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount} | Generated by ProCV Lite Analytics`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });
      }

      // Save the PDF
      doc.save(`ProCV_Analytics_Report_${Date.now()}.pdf`);
      return true;
    } catch (error) {
      console.error("PDF Generation Error:", error);
      throw error;
    }
  }
};
