import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";

import { db, auth } from "../firebase";
import { useAuth } from "../auth/AuthProvider";

import {
  addDoc,
  collection,
  deleteDoc,
  doc,
  onSnapshot,
  orderBy,
  query,
  serverTimestamp,
  updateDoc,
  where,
} from "firebase/firestore";

import { signOut } from "firebase/auth";
import { QRCodeCanvas } from "qrcode.react";

function slugify(text) {
  return (text || "")
    .toString()
    .trim()
    .toLowerCase()
    .replace(/['"]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 50);
}

function makePublishedSlug(base, docId) {
  const cleanBase = slugify(base || "my-cv");
  const shortId = (docId || "").slice(0, 6).toLowerCase();
  return shortId ? `${cleanBase}-${shortId}` : cleanBase;
}

export default function Dashboard() {
  const navigate = useNavigate();
  const { user, loading } = useAuth();

  const [cvs, setCvs] = useState([]);
  const [search, setSearch] = useState("");

  const [shareOpen, setShareOpen] = useState(false);
  const [shareUrl, setShareUrl] = useState("");
  const [shareTitle, setShareTitle] = useState("");

  const [publishOpen, setPublishOpen] = useState(false);
  const [publishCv, setPublishCv] = useState(null);
  const [slugInput, setSlugInput] = useState("");
  const [slugError, setSlugError] = useState("");
  const [publishing, setPublishing] = useState(false);

  useEffect(() => {
    if (loading) return;
    if (!user) return;

    const q = query(
      collection(db, "cvs"),
      where("ownerId", "==", user.uid),
      orderBy("updatedAt", "desc")
    );

    const unsub = onSnapshot(
      q,
      (snap) => {
        const list = snap.docs.map((d) => ({ id: d.id, ...d.data() }));
        setCvs(list);
      },
      (err) => {
        console.error("Dashboard snapshot error:", err);
        alert("Firestore error. Check console.");
      }
    );

    return () => unsub();
  }, [user, loading]);

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return cvs;

    return cvs.filter((cv) => {
      const title = (cv.title || "").toLowerCase();
      const template = (cv.templateId || cv.template || "").toLowerCase();
      const name =
        (cv.cv?.fullName || cv.data?.fullName || cv.fullName || "").toLowerCase();

      return title.includes(q) || template.includes(q) || name.includes(q);
    });
  }, [cvs, search]);

  const getCvTitle = (cv) => {
    return (
      cv.title ||
      cv.cv?.fullName ||
      cv.data?.fullName ||
      cv.fullName ||
      "Untitled CV"
    );
  };

  const getLegacyPublicUrl = (cvId) => `${window.location.origin}/cv/${cvId}`;
  const getPublishedUrl = (slug) => `${window.location.origin}/p/${slug}`;

  const getBestShareUrl = (cv) => {
    if (cv.isPublished && cv.publishedSlug) {
      return getPublishedUrl(cv.publishedSlug);
    }
    return getLegacyPublicUrl(cv.id);
  };

  const handleDelete = async (cvId, title) => {
    const ok = confirm(`Delete "${title || "Untitled CV"}" ?`);
    if (!ok) return;

    try {
      await deleteDoc(doc(db, "cvs", cvId));
    } catch (e) {
      console.error(e);
      alert("❌ Delete failed. Check console.");
    }
  };

  const handleDuplicate = async (cvDoc) => {
    if (!user) return;

    try {
      const baseTitle = getCvTitle(cvDoc);
      const newTitle = `${baseTitle} (Copy)`;

      const payload = {
        ownerId: user.uid,
        title: newTitle,
        cv: cvDoc.cv ||
          cvDoc.data || {
            fullName: "",
            jobTitle: "",
            summary: "",
            photoDataUrl: "",
            photoDataUrlHd: "",
            themeAutoGenerated: null,
            themeMode: "auto",
            themeManual: null,
            skills: [""],
            experience: [
              { role: "", company: "", start: "", end: "", description: "" },
            ],
          },
        templateId: cvDoc.templateId || cvDoc.template || "t1",
        isPublic: false,
        isPublished: false,
        publishedSlug: "",
        publishedAt: null,
        views: 0,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      };

      const docRef = await addDoc(collection(db, "cvs"), payload);
      const openNow = confirm("✅ Duplicated! Open the copy now?");
      if (openNow) navigate(`/builder/${docRef.id}`);
    } catch (e) {
      console.error(e);
      alert("❌ Duplicate failed. Check console.");
    }
  };

  const openShare = async (cv) => {
    if (!cv.isPublic) {
      alert("This CV is Private. Open it in Builder and enable Public Share first.");
      return;
    }

    const url = getBestShareUrl(cv);
    setShareUrl(url);
    setShareTitle(getCvTitle(cv));
    setShareOpen(true);

    try {
      await navigator.clipboard.writeText(url);
    } catch {
      // ignore
    }
  };

  const closeShare = () => {
    setShareOpen(false);
    setShareUrl("");
    setShareTitle("");
  };

  const copyShare = async (value) => {
    try {
      const text = typeof value === "string" ? value : shareUrl;
      await navigator.clipboard.writeText(text);
      alert("✅ Link copied!");
    } catch (e) {
      console.error(e);
      alert("❌ Copy failed. You can manually copy the link.");
    }
  };

  const openPublishModal = (cv) => {
    const base =
      cv.publishedSlug ||
      slugify(cv.cv?.fullName || cv.title || cv.fullName || "my-cv");

    const cleanBase = base.replace(/-[a-z0-9]{6}$/, "");

    setPublishCv(cv);
    setSlugInput(cleanBase);
    setSlugError("");
    setPublishOpen(true);
  };

  const closePublishModal = () => {
    if (publishing) return;
    setPublishOpen(false);
    setPublishCv(null);
    setSlugInput("");
    setSlugError("");
  };

  const validateSlug = (slug) => {
    if (!slug) return "Slug is required.";
    if (slug.length < 3) return "Slug must be at least 3 characters.";
    if (slug.length > 50) return "Slug must be 50 characters or less.";
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) {
      return "Use only lowercase letters, numbers, and hyphens.";
    }
    return "";
  };

  const handlePublish = async () => {
    if (!publishCv) return;

    const cleanBase = slugify(slugInput);
    setSlugInput(cleanBase);

    const validationError = validateSlug(cleanBase);
    if (validationError) {
      setSlugError(validationError);
      return;
    }

    try {
      setPublishing(true);
      setSlugError("");

      const finalSlug = makePublishedSlug(cleanBase, publishCv.id);

      await updateDoc(doc(db, "cvs", publishCv.id), {
        isPublic: true,
        isPublished: true,
        publishedSlug: finalSlug,
        publishedAt: serverTimestamp(),
        updatedAt: serverTimestamp(),
      });

      const publishedUrl = getPublishedUrl(finalSlug);

      setPublishOpen(false);
      setPublishCv(null);
      setSlugInput("");
      setSlugError("");

      try {
        await navigator.clipboard.writeText(publishedUrl);
      } catch {
        // ignore
      }

      alert("✅ CV published!");
    } catch (e) {
      console.error(e);
      setSlugError("Publish failed. Check console.");
    } finally {
      setPublishing(false);
    }
  };

  const handleUnpublish = async (cv) => {
    const ok = confirm(`Unpublish "${getCvTitle(cv)}" ?`);
    if (!ok) return;

    try {
      await updateDoc(doc(db, "cvs", cv.id), {
        isPublished: false,
        publishedSlug: "",
        publishedAt: null,
        updatedAt: serverTimestamp(),
      });
      alert("✅ CV unpublished.");
    } catch (e) {
      console.error(e);
      alert("❌ Unpublish failed. Check console.");
    }
  };

  if (loading) {
    return <div className="p-6">Loading...</div>;
  }

  return (
    <div className="min-h-screen text-white bg-transparent relative z-0">
      <header className="border-b border-white/10 glass-panel">
        <div className="mx-auto max-w-5xl p-4">
          <div className="flex items-center justify-between">
            <div>
              <div className="text-xl font-bold">Dashboard</div>
              <p className="text-sm text-gray-300">Your saved CVs</p>
              <p className="mt-1 text-xs text-gray-400">
                user: {user?.email || user?.uid}
              </p>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={() => navigate("/builder")}
                className="rounded-xl glass-primary-button px-4 py-2 text-sm"
              >
                + New CV
              </button>

              <button
                onClick={() => signOut(auth)}
                className="rounded-xl glass-button px-4 py-2 text-sm"
              >
                Logout
              </button>
            </div>
          </div>

          <div className="mt-4">
            <input
              className="w-full rounded-2xl glass-input px-4 py-3"
              placeholder="Search by title, name, or template..."
              value={search}
              onChange={(e) => setSearch(e.target.value)}
            />
            <div className="mt-2 text-xs text-gray-400">
              Showing {filtered.length} of {cvs.length}
            </div>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-5xl p-4">
        {filtered.length === 0 ? (
          <div className="rounded-2xl glass-panel p-6 text-center text-gray-400">
            No CVs found{search.trim() ? " for your search." : " yet."}
          </div>
        ) : (
          <div className="space-y-3">
            {filtered.map((cv) => {
              const title = getCvTitle(cv);
              const template = cv.templateId || cv.template || "t1";
              const legacyUrl = getLegacyPublicUrl(cv.id);
              const publishedUrl =
                cv.isPublished && cv.publishedSlug
                  ? getPublishedUrl(cv.publishedSlug)
                  : "";

              return (
                <div
                  key={cv.id}
                  className="flex flex-col gap-3 rounded-2xl glass-panel p-4 sm:flex-row sm:items-center sm:justify-between transition-all duration-300 hover:bg-white/5"
                >
                  <div className="min-w-0">
                    <div className="font-semibold">{title}</div>

                    <div className="mt-1 flex flex-wrap items-center gap-2">
                      {cv.isPublished ? (
                        <span className="inline-block rounded-full bg-blue-100 px-2 py-0.5 text-xs text-blue-700">
                          Published
                        </span>
                      ) : cv.isPublic ? (
                        <span className="inline-block rounded-full bg-green-100 px-2 py-0.5 text-xs text-green-700">
                          Public
                        </span>
                      ) : (
                        <span className="inline-block rounded-full bg-gray-100 px-2 py-0.5 text-xs text-gray-600">
                          Private
                        </span>
                      )}

                      <span className="text-xs text-gray-500">
                        Template: {template}
                      </span>

                      {"views" in cv && (
                        <span className="text-xs text-gray-500">
                          Views: {Number(cv.views || 0)}
                        </span>
                      )}
                    </div>

                    {cv.isPublished && publishedUrl ? (
                      <div className="mt-2 break-all text-xs text-gray-400">
                        {publishedUrl}
                      </div>
                    ) : cv.isPublic ? (
                      <div className="mt-2 break-all text-xs text-gray-400">
                        {legacyUrl}
                      </div>
                    ) : null}
                  </div>

                  <div className="flex flex-wrap gap-2 sm:justify-end">
                    {cv.isPublished ? (
                      <>
                        <button
                          onClick={() => copyShare(publishedUrl)}
                          className="rounded-xl glass-button px-4 py-2 text-sm"
                        >
                          Copy Link
                        </button>

                        <button
                          onClick={() => openShare(cv)}
                          className="rounded-xl glass-button px-4 py-2 text-sm"
                        >
                          Share
                        </button>

                        <a
                          href={publishedUrl}
                          target="_blank"
                          rel="noreferrer"
                          className="rounded-xl glass-button px-4 py-2 text-sm"
                        >
                          Open Published
                        </a>

                        <button
                          onClick={() => handleUnpublish(cv)}
                          className="rounded-xl glass-button px-4 py-2 text-sm"
                        >
                          Unpublish
                        </button>
                      </>
                    ) : (
                      <>
                        {cv.isPublic ? (
                          <button
                            onClick={() => openShare(cv)}
                            className="rounded-xl glass-button px-4 py-2 text-sm"
                          >
                            Share
                          </button>
                        ) : (
                          <button
                            onClick={() => openShare(cv)}
                            className="cursor-not-allowed rounded-xl glass-button px-4 py-2 text-sm opacity-50"
                            title="Enable Public Share in Builder to share"
                          >
                            Share
                          </button>
                        )}

                        <button
                          onClick={() => openPublishModal(cv)}
                          className="rounded-xl glass-button px-4 py-2 text-sm"
                        >
                          Publish Now
                        </button>
                      </>
                    )}

                    <button
                      onClick={() => handleDuplicate(cv)}
                      className="rounded-xl glass-button px-4 py-2 text-sm"
                    >
                      Duplicate
                    </button>

                    <button
                      onClick={() => handleDelete(cv.id, title)}
                      className="rounded-xl glass-button px-4 py-2 text-sm"
                    >
                      Delete
                    </button>

                    <button
                      onClick={() => navigate(`/builder/${cv.id}`)}
                      className="rounded-xl glass-primary-button px-4 py-2 text-sm"
                    >
                      Edit
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </main>

      {shareOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
          <div className="w-full max-w-md rounded-2xl glass-panel p-5 shadow-2xl text-white">
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="text-lg font-bold">Share CV</div>
                <div className="text-sm text-gray-300">{shareTitle}</div>
              </div>

                <button
                onClick={closeShare}
                className="rounded-xl glass-button px-3 py-2 text-sm"
              >
                ✕
              </button>
            </div>

            <div className="mt-4 break-all rounded-xl glass-input p-3 text-sm">
              {shareUrl}
            </div>

            <div className="mt-4 flex items-center justify-center">
              <QRCodeCanvas value={shareUrl} size={180} />
            </div>

            <div className="mt-4 flex gap-2">
              <button
                onClick={() => copyShare(shareUrl)}
                className="flex-1 rounded-xl glass-primary-button px-4 py-2 text-sm"
              >
                Copy Link
              </button>

              <a
                href={shareUrl}
                target="_blank"
                rel="noreferrer"
                className="flex-1 rounded-xl glass-button px-4 py-2 text-center text-sm"
              >
                Open
              </a>
            </div>
          </div>
        </div>
      )}

      {publishOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
          <div className="w-full max-w-md rounded-2xl glass-panel p-5 shadow-2xl text-white">
            <div className="flex items-start justify-between gap-4">
              <div>
                <div className="text-lg font-bold">Publish CV</div>
                <div className="text-sm text-gray-300">
                  {publishCv ? getCvTitle(publishCv) : ""}
                </div>
              </div>

              <button
                onClick={closePublishModal}
                className="rounded-xl glass-button px-3 py-2 text-sm"
                disabled={publishing}
              >
                ✕
              </button>
            </div>

            <div className="mt-4">
              <label className="text-sm font-medium">Custom slug</label>
              <input
                className="mt-1 w-full rounded-xl glass-input px-3 py-2"
                placeholder="my-awesome-cv"
                value={slugInput}
                onChange={(e) => {
                  setSlugInput(slugify(e.target.value));
                  setSlugError("");
                }}
              />
              <div className="mt-2 text-xs text-gray-500">
                Your published link will be:
              </div>
              <div className="mt-1 break-all rounded-xl glass-input p-3 text-sm">
                {getPublishedUrl(
                  makePublishedSlug(
                    slugify(slugInput || "my-cv"),
                    publishCv?.id || "demoid"
                  )
                )}
              </div>

              <div className="mt-2 text-xs text-gray-500">
                Publishing will also make this CV public automatically.
              </div>

              {slugError && (
                <div className="mt-3 text-sm text-red-600">{slugError}</div>
              )}
            </div>

            <div className="mt-5 flex gap-2">
              <button
                onClick={handlePublish}
                disabled={publishing}
                className="flex-1 rounded-xl glass-primary-button px-4 py-2 text-sm disabled:opacity-60"
              >
                {publishing ? "Publishing..." : "Publish Now"}
              </button>

              <button
                onClick={closePublishModal}
                disabled={publishing}
                className="flex-1 rounded-xl glass-button px-4 py-2 text-sm disabled:opacity-60"
              >
                Cancel
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}