import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { Download, LayoutDashboard, FileCheck, ArrowLeft } from "lucide-react";
import { useAuth } from "../auth/AuthProvider";

import html2canvas from "html2canvas";
import jsPDF from "jspdf";

import { db } from "../firebase";
import {
  collection,
  doc,
  getDoc,
  getDocs,
  increment,
  limit,
  query,
  runTransaction,
  setDoc,
  where,
} from "firebase/firestore";

import Template1 from "../templates/Template1";
import Template2 from "../templates/Template2";
import Template3 from "../templates/Template3";
import Template4 from "../templates/Template4";
import Template5 from "../templates/Template5";
import Template6 from "../templates/Template6";

export default function PublicCV() {
  const { id, slug } = useParams();

  const [loading, setLoading] = useState(true);
  const [cvDoc, setCvDoc] = useState(null);
  const [error, setError] = useState("");
  const [exportingPdf, setExportingPdf] = useState(false);
  const { user, loading: authLoading } = useAuth();

  const viewCountedRef = useRef(false);
  const visibleCvRef  = useRef(null);

  const templateMap = useMemo(
    () => ({
      t1: Template1,
      t2: Template2,
      t3: Template3,
      t4: Template4,
      t5: Template5,
      t6: Template6,
    }),
    []
  );

  const sanitize = (s) =>
    (s || "")
      .toString()
      .trim()
      .replace(/[<>:"/\\|?*\x00-\x1F]/g, "")
      .replace(/\s+/g, "_");

  useEffect(() => {
    // Wait for auth to initialize before loading CV
    // This ensures we correctly identify the owner even on page refresh
    if (authLoading) return;

    const load = async () => {
      try {
        setLoading(true);
        setError("");
        setCvDoc(null);

        let resolvedDoc = null;
        let ref = null;

        // 1) legacy route: /cv/:id
        if (id) {
          ref = doc(db, "cvs", id);
          const snap = await getDoc(ref);

          if (!snap.exists()) {
            setError("CV not found.");
            setLoading(false);
            return;
          }

          resolvedDoc = { id: snap.id, ...snap.data() };

          // AUTH AWARE: Owners can see their own CV even if not public
          const isOwner = user && resolvedDoc.ownerId === user.uid;

          if (!isOwner && resolvedDoc.isPublic !== true) {
            setError("This CV is private.");
            setLoading(false);
            return;
          }
        }

        // 2) new route: /p/:slug
        if (!resolvedDoc && slug) {
          const q = query(
            collection(db, "cvs"),
            where("publishedSlug", "==", slug),
            where("isPublished", "==", true),
            where("isPublic", "==", true),
            limit(1)
          );

          const snap = await getDocs(q);

          if (snap.empty) {
            setError("Published CV not found.");
            setLoading(false);
            return;
          }

          const first = snap.docs[0];
          resolvedDoc = { id: first.id, ...first.data() };
          ref = doc(db, "cvs", first.id);
        }

        if (!resolvedDoc || !ref) {
          setError("CV not found.");
          setLoading(false);
          return;
        }

        // Increment views only for visitors (not owner)
        if (!viewCountedRef.current && user?.uid !== resolvedDoc.ownerId) {
          viewCountedRef.current = true;
          try {
            // 1) Increment the total view count on the CV doc
            await runTransaction(db, async (tx) => {
              const fresh = await tx.get(ref);
              const cur = fresh.exists() ? Number(fresh.data().views || 0) : 0;
              tx.update(ref, { views: cur + 1 });
            });

            // 2) Write a daily log so the dashboard chart has real data
            const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
            const ownerId = resolvedDoc.ownerId;
            if (ownerId) {
              const dayRef = doc(db, "viewLogs", ownerId, "days", today);
              await setDoc(dayRef, { views: increment(1), date: today }, { merge: true });
            }
          } catch (e) {
            console.warn("Views increment failed:", e);
          }
        }

        setCvDoc(resolvedDoc);
        setLoading(false);
      } catch (e) {
        console.error(e);
        setError("Failed to load CV.");
        setLoading(false);
      }
    };

    load();
  }, [id, slug, user, authLoading]);

  const rawCv = useMemo(() => {
    return cvDoc?.cv || cvDoc?.data || cvDoc || null;
  }, [cvDoc]);

  const effectiveTheme = useMemo(() => {
    if (!rawCv) return null;
    if (rawCv.themeMode === "default") return null;
    if (rawCv.themeMode === "manual" && rawCv.themeManual) return rawCv.themeManual;
    return rawCv.themeAutoGenerated || null;
  }, [rawCv]);

  const cvForRender = useMemo(() => {
    if (!rawCv) return null;
    return {
      ...rawCv,
      theme: effectiveTheme,
    };
  }, [rawCv, effectiveTheme]);

  const templateId = cvDoc?.templateId || "t1";
  const SelectedTemplate = templateMap[templateId] || Template1;

  const isOwner = user && cvDoc && user.uid === cvDoc.ownerId;

  const pageTitle = useMemo(() => {
    if (cvDoc?.isPublished && cvDoc?.publishedSlug) {
      return cvForRender?.fullName
        ? `${cvForRender.fullName} • Published CV`
        : "Published CV";
    }
    return cvForRender?.fullName
      ? `${cvForRender.fullName} • Public CV`
      : "Public CV";
  }, [cvDoc, cvForRender]);

  const downloadPdf = async () => {
    try {
      setExportingPdf(true);

      // Wait for off-screen element to fully paint
      await new Promise((r) => setTimeout(r, 700));

      const el = visibleCvRef.current;
      if (!el) {
        alert("Preview not ready. Try again.");
        setExportingPdf(false);
        return;
      }

      // Capture exact rendered dimensions
      const naturalW = el.scrollWidth  || 794;
      const naturalH = el.scrollHeight || 1123;

      const canvas = await html2canvas(el, {
        scale: 2.5,
        useCORS: true,
        allowTaint: true,
        backgroundColor: "#ffffff",
        scrollX: 0,
        scrollY: 0,
        width: naturalW,
        height: naturalH,
        windowWidth: naturalW,
        windowHeight: naturalH,
      });

      if (!canvas?.width || !canvas?.height) {
        alert("PDF capture failed. Try again.");
        setExportingPdf(false);
        return;
      }

      const imgData = canvas.toDataURL("image/jpeg", 0.96);

      // Standard A4 in points
      const A4_W = 595.28;
      const A4_H = 841.89;

      // Scaled image height when fitted to A4 width
      const scaledH = (canvas.height / canvas.width) * A4_W;

      let pdf;

      if (scaledH <= A4_H * 1.2) {
        // ─── Fits in one A4 page (scale to fill exactly) ─────────────
        pdf = new jsPDF("p", "pt", "a4");
        pdf.addImage(imgData, "JPEG", 0, 0, A4_W, Math.min(scaledH, A4_H));
      } else {
        // ─── Multi-page: tile the full image across pages ──────────────
        pdf = new jsPDF("p", "pt", "a4");
        let heightLeft = scaledH;
        let position   = 0;

        pdf.addImage(imgData, "JPEG", 0, position, A4_W, scaledH);
        heightLeft -= A4_H;

        while (heightLeft > 1) {
          position   -= A4_H;
          pdf.addPage();
          pdf.addImage(imgData, "JPEG", 0, position, A4_W, scaledH);
          heightLeft -= A4_H;
        }
      }

      const fileName = `${sanitize(cvForRender?.fullName || "cv")}_${sanitize(templateId)}.pdf`;
      pdf.save(fileName);
    } catch (err) {
      console.error(err);
      alert("PDF generation failed. Check Console (F12).");
    } finally {
      setExportingPdf(false);
    }
  };

  if (loading) {
    return (
      <div className="flex h-screen items-center justify-center bg-[#0A0D14]">
        <div className="flex flex-col items-center gap-4">
          <div className="h-10 w-10 animate-spin rounded-full border-4 border-indigo-600/30 border-t-indigo-600" />
          <p className="text-gray-400 font-medium">Loading CV...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex h-screen items-center justify-center bg-[#0A0D14]">
        <div className="rounded-2xl border border-white/5 bg-[#111622] p-8 max-w-md w-full text-center shadow-2xl">
          <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-red-500/10">
             <FileCheck className="h-7 w-7 text-red-500" />
          </div>
          <h2 className="text-xl font-bold text-white mb-2">Oops!</h2>
          <p className="text-gray-400 mb-6">{error}</p>
          <Link 
            to={user ? "/dashboard" : "/"} 
            className="inline-block rounded-xl bg-indigo-600 px-6 py-2.5 font-medium text-white hover:bg-indigo-700 transition-colors"
          >
            {user ? "Back to Dashboard" : "Back to Home"}
          </Link>
        </div>
      </div>
    );
  }

  if (!cvForRender) {
    return (
      <div className="flex h-screen items-center justify-center bg-[#0A0D14]">
        <div className="rounded-2xl border border-white/5 bg-[#111622] p-8 max-w-md w-full text-center shadow-2xl">
          <p className="text-red-400 font-medium mb-4">CV data is missing.</p>
           <Link 
            to={user ? "/dashboard" : "/"} 
            className="inline-block rounded-xl bg-indigo-600 px-6 py-2.5 font-medium text-white hover:bg-indigo-700 transition-colors"
          >
            {user ? "Back to Dashboard" : "Back to Home"}
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#0A0D14] text-white font-sans selection:bg-indigo-500/30 pb-12 custom-scrollbar">
      {/* HEADER */}
      <header className="sticky top-0 z-40 border-b border-white/5 bg-[#0A0D14]/80 backdrop-blur-xl">
        <div className="mx-auto flex max-w-6xl items-center justify-between p-4">
          <div className="flex items-center gap-3">
             <div className="bg-white/10 p-2 rounded-lg">
                <FileCheck className="w-5 h-5 text-indigo-400" />
             </div>
            <div>
              <div className="font-bold text-gray-100">{cvDoc?.isPublished ? "Published CV" : "Public CV"}</div>
              <p className="text-[12px] text-gray-400 mt-0.5">
                {pageTitle}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <Link
              className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-4 py-2.5 text-sm font-medium hover:bg-white/10 transition-colors"
              to={isOwner ? "/dashboard" : (user ? "/dashboard" : "/")}
            >
              {isOwner ? (
                <>
                  <LayoutDashboard className="w-4 h-4" />
                  <span className="hidden sm:inline">Back to Dashboard</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-indigo-400" />
                  <span className="hidden sm:inline">Build your own CV</span>
                </>
              )}
            </Link>
            <button
              onClick={downloadPdf}
              disabled={exportingPdf}
              className="flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-medium text-white hover:bg-indigo-500 disabled:opacity-50 transition-colors shadow-lg shadow-indigo-500/20"
            >
              <Download className="w-4 h-4" />
              {exportingPdf ? "Generating..." : "Download PDF"}
            </button>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-6xl mt-8 px-4 flex justify-center">
        <div className="w-full max-w-[850px] overflow-x-auto custom-scrollbar rounded-2xl border border-white/10 bg-[#111622] p-4 sm:p-6 shadow-2xl">
          <div
            ref={visibleCvRef}
            className="mx-auto bg-white rounded-sm overflow-hidden shadow-md"
            style={{ minWidth: '794px', width: '794px' }}
          >
            <SelectedTemplate cv={{ ...cvForRender, photoDataUrl: cvForRender.photoDataUrlHd || cvForRender.photoDataUrl }} />
          </div>
        </div>
      </main>
    </div>
  );
}