import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";

import html2canvas from "html2canvas";
import jsPDF from "jspdf";

import { db } from "../firebase";
import {
  collection,
  doc,
  getDoc,
  getDocs,
  limit,
  query,
  runTransaction,
  where,
} from "firebase/firestore";

import Template1 from "../templates/Template1";
import Template2 from "../templates/Template2";
import Template3 from "../templates/Template3";
import Template4 from "../templates/Template4";
import Template5 from "../templates/Template5";
import Template6 from "../templates/Template6";

export default function PublicCV() {
  const { id, slug } = useParams();

  const [loading, setLoading] = useState(true);
  const [cvDoc, setCvDoc] = useState(null);
  const [error, setError] = useState("");
  const [exportingPdf, setExportingPdf] = useState(false);

  const viewCountedRef = useRef(false);
  const pdfRef = useRef(null);

  const templateMap = useMemo(
    () => ({
      t1: Template1,
      t2: Template2,
      t3: Template3,
      t4: Template4,
      t5: Template5,
      t6: Template6,
    }),
    []
  );

  const sanitize = (s) =>
    (s || "")
      .toString()
      .trim()
      .replace(/[<>:"/\\|?*\x00-\x1F]/g, "")
      .replace(/\s+/g, "_");

  useEffect(() => {
    const load = async () => {
      try {
        setLoading(true);
        setError("");
        setCvDoc(null);

        let resolvedDoc = null;
        let ref = null;

        // 1) legacy route: /cv/:id
        if (id) {
          ref = doc(db, "cvs", id);
          const snap = await getDoc(ref);

          if (!snap.exists()) {
            setError("CV not found.");
            setLoading(false);
            return;
          }

          resolvedDoc = { id: snap.id, ...snap.data() };

          if (resolvedDoc.isPublic !== true) {
            setError("This CV is private.");
            setLoading(false);
            return;
          }
        }

        // 2) new route: /p/:slug
        if (!resolvedDoc && slug) {
          const q = query(
            collection(db, "cvs"),
            where("publishedSlug", "==", slug),
            where("isPublished", "==", true),
            where("isPublic", "==", true),
            limit(1)
          );

          const snap = await getDocs(q);

          if (snap.empty) {
            setError("Published CV not found.");
            setLoading(false);
            return;
          }

          const first = snap.docs[0];
          resolvedDoc = { id: first.id, ...first.data() };
          ref = doc(db, "cvs", first.id);
        }

        if (!resolvedDoc || !ref) {
          setError("CV not found.");
          setLoading(false);
          return;
        }

        if (!viewCountedRef.current) {
          viewCountedRef.current = true;
          try {
            await runTransaction(db, async (tx) => {
              const fresh = await tx.get(ref);
              const cur = fresh.exists() ? Number(fresh.data().views || 0) : 0;
              tx.update(ref, { views: cur + 1 });
            });
          } catch (e) {
            console.warn("Views increment failed:", e);
          }
        }

        setCvDoc(resolvedDoc);
        setLoading(false);
      } catch (e) {
        console.error(e);
        setError("Failed to load CV.");
        setLoading(false);
      }
    };

    load();
  }, [id, slug]);

  const rawCv = useMemo(() => {
    return cvDoc?.cv || cvDoc?.data || cvDoc || null;
  }, [cvDoc]);

  const effectiveTheme = useMemo(() => {
    if (!rawCv) return null;
    if (rawCv.themeMode === "manual" && rawCv.themeManual) return rawCv.themeManual;
    return rawCv.themeAutoGenerated || null;
  }, [rawCv]);

  const cvForRender = useMemo(() => {
    if (!rawCv) return null;
    return {
      ...rawCv,
      theme: effectiveTheme,
    };
  }, [rawCv, effectiveTheme]);

  const templateId = cvDoc?.templateId || "t1";
  const SelectedTemplate = templateMap[templateId] || Template1;

  const pageTitle = useMemo(() => {
    if (cvDoc?.isPublished && cvDoc?.publishedSlug) {
      return cvForRender?.fullName
        ? `${cvForRender.fullName} • Published CV`
        : "Published CV";
    }
    return cvForRender?.fullName
      ? `${cvForRender.fullName} • Public CV`
      : "Public CV";
  }, [cvDoc, cvForRender]);

  const downloadPdf = async () => {
    try {
      setExportingPdf(true);
      await new Promise((r) => setTimeout(r, 400));

      const el = pdfRef.current;
      if (!el) {
        alert("Preview not ready. Try again.");
        return;
      }

      const canvas = await html2canvas(el, {
        scale: 3,
        useCORS: true,
        backgroundColor: "#ffffff",
        windowWidth: 794,
        scrollX: 0,
        scrollY: 0,
      });

      if (!canvas?.width || !canvas?.height) {
        alert("PDF capture failed. Try again.");
        return;
      }

      const imgData = canvas.toDataURL("image/png");

      const pdf = new jsPDF("p", "pt", "a4");
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();

      const imgWidth = pageWidth;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      let y = 0;
      let remaining = imgHeight;

      pdf.addImage(imgData, "PNG", 0, y, imgWidth, imgHeight);
      remaining -= pageHeight;

      while (remaining > 0) {
        pdf.addPage();
        y -= pageHeight;
        pdf.addImage(imgData, "PNG", 0, y, imgWidth, imgHeight);
        remaining -= pageHeight;
      }

      const fileName = `${sanitize(cvForRender?.fullName || "cv")}_${sanitize(
        templateId
      )}.pdf`;

      pdf.save(fileName);
    } catch (err) {
      console.error(err);
      alert("PDF generation failed. Check Console (F12).");
    } finally {
      setExportingPdf(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 p-6">
        <div className="mx-auto max-w-4xl rounded-2xl border bg-white p-6">
          Loading...
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gray-50 p-6">
        <div className="mx-auto max-w-4xl rounded-2xl border bg-white p-6">
          <div className="font-semibold text-red-600">{error}</div>
          <div className="mt-4">
            <Link className="underline" to="/">
              Back to Login
            </Link>
          </div>
        </div>
      </div>
    );
  }

  if (!cvForRender) {
    return (
      <div className="min-h-screen bg-gray-50 p-6">
        <div className="mx-auto max-w-4xl rounded-2xl border bg-white p-6">
          <div className="font-semibold text-red-600">CV data is missing.</div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b bg-white">
        <div className="mx-auto flex max-w-6xl items-center justify-between p-4">
          <div>
            <div className="font-bold">{cvDoc?.isPublished ? "Published CV" : "Public CV"}</div>
            <p className="text-sm text-gray-600">
              {pageTitle} • {templateId}
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={downloadPdf}
              disabled={exportingPdf}
              className="rounded-xl bg-black px-4 py-2 text-sm text-white hover:opacity-90 disabled:opacity-60"
            >
              {exportingPdf ? "Generating..." : "Download PDF"}
            </button>

            <a
              className="rounded-xl border px-3 py-2 text-sm hover:bg-gray-50"
              href="/"
            >
              Login
            </a>
          </div>
        </div>
      </header>

      <main className="mx-auto max-w-6xl p-6">
        <div className="rounded-2xl border bg-white p-4 shadow-sm">
          <SelectedTemplate cv={cvForRender} />
        </div>

        {exportingPdf && (
          <div
            ref={pdfRef}
            style={{
              position: "fixed",
              left: 0,
              top: 0,
              width: "794px",
              background: "white",
              pointerEvents: "none",
              zIndex: 1,
            }}
          >
            <SelectedTemplate
              cv={{
                ...cvForRender,
                photoDataUrl: cvForRender.photoDataUrlHd || cvForRender.photoDataUrl,
              }}
            />
          </div>
        )}
      </main>
    </div>
  );
}